### ISSUE TITLE
vtc_record() loops indefinitely when fd is half-closed

### ISSUE THREAD

**Issue by bzakhar** [vtest/VTest#14]
On Cygwin (and maybe other platforms), vtc_record() main loop never exits even though remote side terminates or hangs up. This seems to be due to Cygwin poll() not raising POLLHUP or POLLERR flags when this happens, which is the only condition to break out of the loop. Instead, poll() returns immediately with POLLIN flag raised and subsequent read() returns 0 bytes from the fd. Neither function returns errors (but even if they did, negative returns are not handled in vtc_record() either).

Attached is a proposed patch to cope with this behavior and also handle poll/read errors gracefully.
[poll.patch.txt](https://github.com/vtest/VTest/files/3257997/poll.patch.txt)

**Comment by bsdphk** [comment]
In 53c6226cb7c656ae0 I have simplified vtc_record() to get rid of the poll(2) entirely.
