### ISSUE TITLE
mixing ipv4 / ipv6

### ISSUE THREAD

**Issue by chipitsine** [vtest/VTest#23]
can you please have a look https://github.com/haproxy/haproxy/commit/2aa3dd2b4318eddf54e3958e7cd5751b0e25db74 ?

I confirm that it is not random issue. We did not see it in travis-ci, I guess because travis-ci runs without ipv6.
When I run similar tests on Linux with ipv6 enabled, I saw the same `127.0.0.1` <--> `::1` mix, i.e. `${h1_px_addr}` was set to different families

**Comment by bsdphk** [comment]
Was this fixed by pull-request #24 so we can close this ticket ?
