### ISSUE TITLE
Assert error in macro_get(), src/vtc.c line 228 on macOS

### ISSUE THREAD

**Issue by TimWolla** [vtest/VTest#26]
It appears that the changes that were pushed yesterday broke VTest on macOS. In HAProxy we're seeing that macOS started failing all tests (while Linux continues to suceed).

The output is:

```
Assert error in macro_get(), src/vtc.c line 228:
  Condition((pthread_mutex_lock(&macro_mtx)) == 0) not true.
```

The line in question is this one: https://github.com/vtest/VTest/blob/f051940ea16563aee34da29533005e817c96a287/src/vtc.c#L228

You can find an example run here: https://github.com/haproxy/haproxy/runs/1681337658#step:12:156

Unfortunately I can't give any more details as of right now, due to the lack of a macOS machine. If you need any further information I'll be happy to attempt to get it.

**Comment by nigoroll** [comment]
Apologies for having caused this issue.
Does this patch by @Dridi work for you? https://github.com/varnishcache/varnish-cache/commit/f855fa46fb1ad66f16e264d57129d605e87f33c4
Other than that a different solution is both possible and simple, using `macro_get()` just seemed convenient.

**Comment by nigoroll** [comment]
nevermind, the actual fix is here: https://github.com/varnishcache/varnish-cache/commit/c79419bf0279f3e2f7be3389388f1c4fe584fe15

**Comment by TimWolla** [comment]
> Does this patch by @Dridi work for you?

Testing patches on top of VTest master is not exactly easy in GitHub Actions, it requires cluttering the commit history with useless patches (especially if it does *not* work out).

In HAProxy we consume the current master of VTest (we could however easily roll back to an earlier commit): https://github.com/haproxy/haproxy/blob/6ecd59326f7416dcba215f05a6674d4b9f970749/.github/workflows/vtest.yml#L61-L67

So I guess depending on when VTest is going to be updated from Varnish we'll either wait or roll back to the last known working commit.

In any case: Thanks for the already quick turnaround time!

**Comment by jmagnin** [comment]
> Apologies for having caused this issue.
> Does this patch by @Dridi work for you?

The fix works for me.
