### ISSUE TITLE
Make failed with fatal error: 'pcre2.h' file not found

### ISSUE THREAD

**Issue by dhruvjain99** [vtest/VTest#30]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/51796498/159236814-ea128bb6-777c-4ae9-b010-647ccd67e795.png">

**Comment by dhruvjain99** [comment]
`brew install pcre2` solved the issue.

**Comment by bsdphk** [comment]
Sorry about the primitive build environment for VTEST.
