### ISSUE TITLE
server -break 

### ISSUE THREAD

**Issue by haproxyFred** [vtest/VTest#6]
Are not the server threads supposed to close their listening sockets before being pthread_join()'ed with "-break" command?

**Comment by bsdphk** [comment]
Yes, I think it should.

Patch welcome :-)

**Comment by haproxyFred** [comment]
Hello Poul-Henning,
I have just created a pull request for this issue (see https://github.com/vtest/VTest/pull/15).

Regards,
Fred.

**Comment by haproxyFred** [comment]
Fixed by e1a2800 commit.
